version: "3.7"
services:
  kony:
      build:
        context: ./kony-mysql
        dockerfile: Dockerfile
      ports:
        - 8181:80
        - 8080:8080
      environment:
        - MYSQL_DATABASE:kony
      networks:
        - centos-mysql
  db:
      image: mysql:5.7
      volumes:
        - ./db_data:/var/lib/mysql
      restart: always
      ports:
        - 3306:3306
      networks:
        - centos-mysql  
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: kony
        MYSQL_USER: kony
        MYSQL_PASSWORD: konypass    
networks:
      centos-mysql:        